#!/bin/bash

export disk="/dev/nvme0n1"                                 # The disk you would like to install arch on (eg /dev/sda or /dev/nvme0n1)
export wipe=true                                           # Do you want to wipe the disk? If you don't, it will just default to two more partitions
export kernel="linux"                                      # The name of the kernel you would like to install (eg linux, linux-lts, linux-zen)
export hostname="jason"                                    # Hostname of machine
export username="jason"                                    # Username of the main user
export timezone="US/Eastern"                               # /usr/share/zoneinfo/<region>/<location>
export locale="en_US"                                      # Your locale
export language="en_US"                                    # Your language in locale.conf
export aurhelper="paru-bin"                                # Which AUR helper do you want (just installs it from the AUR)
export installdotfiles=true                                # You need a good AUR helper for this because it installs yadm from the AUR
export dotfilesurl="https://github.com/jso8910/dotfiles"   # URL of your dotfiles repo (only used if installdotfiles=true
export multilib=true                                       # Enable the multilib repos?
export swapfilesize=16000                                  # Size of swapfile (in MB)
export userpassword="password"                             # User's password (mandatory)
export rootpassword=""                                     # Root password (blank by default)
export cryptpassword="password"                            # Encryption password (mandatory)
export isopart=true                                        # Do you want a partition for the ISO?

# Partition layout example
# /dev/sda1: /boot
# /dev/sda2: luks cryptroot
# /dev/mapper/cryptroot: btrfs
# Top level subvolumes:
# @: mounted to /
# @home: mounted to /home
# @swap: mounted to /.swap
# @var_log: mounted to /var/log
# @snapshots: mounted to /.snapshots
